# Site settings
title: Karina's Blog (@TryKatChup)
description: >-
  My personal website  <a href="https://github.com/TryKatChup" target="_blank" rel="noopener">@github</a>.
lang: en-US
timezone: Rome/Europe
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/TryKatChup/TryKatchup.github.io
mode: "dark" # default theme "dark" | "light"

# Profile settings
author:
  name: Karina
  bio: >-
    My personal website <a href="https://github.com/TryKatChup" target="_blank" rel="noopener">@github</a>.
  username: TryKatChup
  email: 
  open_to_work: true
  avatar: /assets/img/avatar.png

# Url settings
url: "https://trykatchup.github.io"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:
social_links:
    twitter: karychan007
    github:  TryKatChup
    linkedin_username: karina-chichifoi
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll
    
disqus:
  shortname: 'TryKatChup'

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      icon: "💭️"
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - bangsring.gemspec
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
